wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 25, 32, 32, 90]
    rows: [6, 3, 10, 4, 4, 90]
  refreshInterval: 1
  openFileUtil: "open"
  openUrlUtil:
    - "tmux"
    - "new-window"
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Yerevan: "Asia/Yerevan"
        Toronto: "America/Toronto"
        London: "Europe/London"
        Seattle: "America/Los_Angeles"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "Clocks A"
      type: "clocks"
    # feedreader:
    #   enabled: true
    #   feeds:
    #   - 
    #   feedLimit: 5
    #   position:
    #     top: 1
    #     left: 1
    #     width: 2
    #     height: 1
    #   refreshInterval: 14400
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 1
        left: 1
        height: 2
        width: 1
      refreshInterval: 15
      title: "⚡️"
    # textfile:
    #   enabled: true
    #   filePath: "~/.config/wtf/config.yml"
    #   format: true
    #   position:
    #     top: 0
    #     left: 0
    #     height: 4
    #     width: 1
    #   refreshInterval: 30
    #   wrapText: false
    uptime:
      args: []
      cmd: "uptime"
      enabled: true
      position:
        top: 1
        left: 2
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
    tmux:
      args: ["ls"]
      cmd: "tmux"
      enabled: true
      position:
        top: 0
        left: 2
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
    gpus:
      args: []
      cmd: "nvidia-smi"
      enabled: true
      position:
        top: 2
        left: 1
        height: 3
        width: 3
      refreshInterval: 30
      type: cmdrunner
    github:
      baseURL: ""
      # customQueries:
      #   othersPRs:
      #     title: "Others Pull Requests"
      #     filter: "is:open is:pr -author:wtfutil"
      enabled: true
      enableStatus: true
      position:
        top: 1
        left: 0
        height: 3
        width: 1
      refreshInterval: 5m
      repositories:
        - "yerevann/ChemLactica"
      uploadURL: ""
      username: "wtfutil"
